version: 0.2

env:
  git-credential-helper: yes

phases:

  build:
    commands:
      # Just do enough to clone and jump to the private repository
      - git clone https://github.com/circlefin/payments-sample-app-private.git
      - payments-sample-app-private/bin/buildspec_deploy.sh
